'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Settings

    '''<summary>
    '''lblApiKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApiKey As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtApiKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApiKey As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdLoadLists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdLoadLists As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblList As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''drpLists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpLists As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblUseDoubleOptIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUseDoubleOptIn As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkUseDoubleOptIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUseDoubleOptIn As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblSendWelcomeEmailOnSubscribe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSendWelcomeEmailOnSubscribe As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkSendWelcomeEmailOnSubscribe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSendWelcomeEmailOnSubscribe As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblDeleteMemberOnUnsubscribe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeleteMemberOnUnsubscribe As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkDeleteMemberOnUnsubscribe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDeleteMemberOnUnsubscribe As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblSendGoodbyEmailOnUnSubscribe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSendGoodbyEmailOnUnSubscribe As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkSendGoodbyEmailOnUnSubscribe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSendGoodbyEmailOnUnSubscribe As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblSendAdminNotificationOnUnsubscribe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSendAdminNotificationOnUnsubscribe As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkSendAdminNotificationOnUnsubscribe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSendAdminNotificationOnUnsubscribe As Global.System.Web.UI.WebControls.CheckBox
End Class
