'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Templates

    '''<summary>
    '''plTheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plTheme As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''drpThemes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpThemes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmdCopySelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCopySelected As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cmdDeleteSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDeleteSelected As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlLocales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLocales As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''plLocale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plLocale As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''drpLocales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpLocales As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''plUseTheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plUseTheme As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkUseTheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUseTheme As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlTemplateName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTemplateName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''plTemplateName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plTemplateName As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtTemplateName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTemplateName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MailChimpTemplatesTabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MailChimpTemplatesTabs As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblFormSubscribe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormSubscribe As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFormSubscribeResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormSubscribeResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUnSubscribe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnSubscribe As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUnSubscribeResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnSubscribeResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSettings As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSettingsResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSettingsResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFormSubscribe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFormSubscribe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFormSubscribeResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFormSubscribeResult As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUnSubscribe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnSubscribe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUnSubscribeResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnSubscribeResult As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSettings As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSettingsResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSettingsResult As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdUpdateSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpdateSettings As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cmdCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
End Class
